name: Update Student Repositories

on:
  push:
    branches:
      - main

jobs:
  update-student-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get list of student repositories
        run: |
          # Получение списка репозиториев студентов
          STUDENT_REPOS=$(gh repo list --json name --jq '.[] | .name')
          echo "STUDENT_REPOS=$STUDENT_REPOS" >> $GITHUB_ENV

      - name: Update each student repository
        run: |
          # Обновление каждого репозитория студента
          for REPO in $STUDENT_REPOS; do
            echo "Updating $REPO"
            gh repo sync $REPO --source $GITHUB_REPOSITORY
          done
